version: '3.9'

services:
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .DBdata:/var/lib/mysql
    ports:
      - 33066:3306